### ISSUE TITLE
Fix zoffset implementation

### ISSUE THREAD

**Issue by jeffreydemieville** [phytooracle/rgb_bin2tif#1]
Modify implementation of zoffset argument:
REMOVE: default=0.76
ADD: required=True
ADD: # Check with gantry operator for correct height for specified season

**Comment by jeffreydemieville** [comment]
Note to also check TYPE for argument. It's currently defined as an 'int'.

**Comment by emmanuelgonz** [comment]
The argument type is correctly specified as float. The default value of 0.76 was removed and the argument was set as required, meaning that each YAML will need to specify this value within the "command" section otherwise it will fail.

The associated [YAML file](https://github.com/phytooracle/automation/blob/main/yaml_files/season_14/stereoTop_level01_s14_reprocessing) now includes `-z 1.131` in the "command" section of Module 1.

This resolves the issue.
